<a href="https://colab.research.google.com/github/12manisha/artificial_neural_network/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [24]:
tf.__version__

'2.15.0'

In [25]:
dataset = pd.read_csv('Churn_Modelling.csv')
x = dataset.iloc[:, 3:-1].values
y = dataset.iloc[: ,-1].values

In [26]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,2] = le.fit_transform(x[:,2])

In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),  [1] ) ], remainder = 'passthrough')
x=np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [29]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

**BUILDING ANN**

In [30]:
ann = tf.keras.models.Sequential()

In [31]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [32]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [33]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

**TRAINING ANN**

In [34]:
ann.compile(optimizer='adam', loss='binary_crossentropy' ,metrics='accuracy')

In [35]:
ann.fit(x_train,y_train,batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.6621 - accuracy: 0.6315
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4861 - accuracy: 0.7837
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4487 - accuracy: 0.8009
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4265 - accuracy: 0.8164
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4125 - accuracy: 0.8245
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4010 - accuracy: 0.8319
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3905 - accuracy: 0.8391
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3797 - accuracy: 0.8465
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3690 - accuracy: 0.8496
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3604 - accura

**Predicting the result**

In [36]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 57ms/step
[[False]]


**PREDICTING TEST SET RESULT**

In [37]:
y_pred = ann.predict(x_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1) , y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 899us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [38]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1509   86]
 [ 188  217]]


0.863